#!/usr/bin/env python3
"""Build scenes/cues.js: for each beat, the start time (s) of named phrases in the narration.
Phrases are searched in order in captions/words-NN.json (whisper word timings)."""
import json, re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
PHRASES = {
    "01": {"customer": "customer in", "nobody": "nobody", "four": "four seconds"},
    "03": {"showroom": "showroom", "products": "34 products|thirty-four", "search": "live search", "stock": "real stock", "checks": "checks out", "oneThing": "does one thing", "payload": "single json|json payload", "endpoint": "single endpoint"},
    "04": {"route": "workflow 13|workflow thirteen", "everyAction": "every action", "routedByName": "routed by", "handsOff": "hands off", "wf10": "workflow ten|workflow 10", "validates": "validates", "decrements": "decrements", "customer": "creates the customer", "order": "writes the order", "invoice": "its invoice", "task": "opens a task", "ship": "ship this", "human": "for a human", "twice": "send the same", "noDuplicates": "no duplicates"},
    "05": {"lands": "lands in", "six": "six tables", "orders": "orders", "invoices": "invoices", "customers": "customers", "products": "products", "leads": "leads", "tasks": "tasks", "status": "every status", "relation": "every relation", "boring": "boring", "fifteen": "fifteen workflows|15 workflows", "step": "step on"},
    "06": {"wakes": "wakes up", "vat": "18%|eighteen percent", "wf8": "workflow eight|workflow 8", "html": "as html", "gotenberg": "gotenberg|gutenberg|gottenberg|ships it", "drive": "google drive", "email": "gets an email", "tracking": "tracking link", "orderPage": "order page", "telegram": "i get a telegram", "saw": "message you saw"},
    "07": {"waiting": "waiting for me", "flags": "flags anything", "open": "i open the order", "shipped": "mark it shipped|marked it shipped|shipped", "closes": "closes itself", "stock": "stock is live", "warning": "warning light"},
    "08": {"easy": "easy part", "three": "three ai agents", "support": "support agent", "buttons": "with buttons", "interested": "interested", "phone": "phone number", "lead": "a lead lands", "talk": "just talk", "grounded": "grounded", "vector": "vector store", "discount": "discount", "refuses": "refuses", "humanAsk": "ask for a human", "hands": "hands you off", "manager": "manager agent", "revenue": "revenue", "sales": "sales agent", "reply": "reply"},
    "09": {"brief": "the brief", "revenue": "live revenue", "feed": "a feed", "chat": "a chat", "keystroke": "keystroke"},
    "10": {"workflows": "fifteen n|15 n", "tables": "six airtable|6 airtable|six air|6 air|airtable tables", "agents": "three agents", "bots": "telegram bots", "apps": "next", "vector": "vector store", "pdf": "pdf engine", "tests": "test suite"},
    "11": {"one": "one order", "fifteen": "fifteen workflows|15 workflows", "zero": "zero manual", "built": "built by"},
}
def norm(s): return re.sub(r"[^a-z0-9% ]+", "", s.lower())
out = {}
for beat, phrases in PHRASES.items():
    words = json.load(open(root / "captions" / f"words-{beat}.json"))
    toks = [norm(w["text"]) for w in words]
    text = " ".join(toks)
    # map char offset -> word index
    starts, pos = [], 0
    for tk in toks:
        starts.append(pos); pos += len(tk) + 1
    cues, cursor = {}, 0
    for key, alts in phrases.items():
        hit = None
        for alt in alts.split("|"):
            i = text.find(norm(alt), cursor)
            if i >= 0 and (hit is None or i < hit): hit = i
        if hit is None:
            print(f"  beat {beat}: phrase not found for {key!r} ({alts})"); continue
        wi = max(j for j, st in enumerate(starts) if st <= hit)
        cues[key] = round(words[wi]["start"], 2); cursor = hit
    out[beat] = cues
    print(beat, cues)
js = "// Generated by scripts/cues.py from captions/words-NN.json (whisper). Seconds into each beat's narration.\nwindow.CUES = " + json.dumps(out) + ";\n"
(root / "scenes" / "cues.js").write_text(js)
print("wrote scenes/cues.js")
